// Package docs serves the API documentation: the Swagger UI, and the OpenAPI
// document it renders.
//
// Nothing here is written by hand except this file. The spec is generated by swag
// from the annotations on main.go and the controllers, and the UI is the real
// Swagger UI shipped by swaggo/files — there is no hand-maintained HTML page.
//
// The file is named handler.go rather than docs.go so it can never collide with
// generated output.
package docs

import (
	_ "embed"
	"net/http"

	httpSwagger "github.com/swaggo/http-swagger/v2"
)

// SpecPath is where the OpenAPI document is served, and what the UI is pointed at.
const SpecPath = "/openapi.yaml"

// spec is the generated OpenAPI 3.0.3 document, embedded at build time so the
// binary is self-contained and has no runtime file dependency.
//
// Regenerate with `go run ./cmd/gendocs` after changing a route, a DTO, or an
// annotation, and commit the result — the Docker build embeds it and must not need
// the swag binary. Generation uses --ot yaml,json, which skips docs.go: swag is a
// build-time tool only and the server never links its runtime.
//
// swag emits 3.1, which gendocs retags to 3.0.3 because the bundled Swagger UI
// cannot render 3.1. See cmd/gendocs for the full reasoning and the guard.
//
//go:embed swagger.yaml
var spec []byte

// Controller serves the documentation routes.
type Controller struct {
	ui http.HandlerFunc
}

// NewController returns a documentation controller.
//
// The UI is pointed at SpecPath rather than swag's registered doc.json on purpose:
// http-swagger reads that registry through swag v1, while the spec is generated by
// swag v2, and the two registries are separate. Serving the embedded document
// ourselves sidesteps that mismatch and keeps the spec version entirely our choice.
func NewController() *Controller {
	return &Controller{
		ui: httpSwagger.Handler(httpSwagger.URL(SpecPath)),
	}
}

// UI serves Swagger UI. It is mounted as a subtree because the UI requests its own
// assets (index.html, the stylesheet, the bundle) beneath that prefix.
func (c *Controller) UI(w http.ResponseWriter, r *http.Request) {
	c.ui(w, r)
}

// Spec serves the embedded OpenAPI document.
func (c *Controller) Spec(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/yaml")
	_, _ = w.Write(spec)
}
